# Micrososft Visual Studio Extensions
vscode_extensions:
  - redhat.vscode-yaml
  - samuelcolvin.jinjahtml
  - ms-python.python
  - ms-vscode.PowerShell
  - vscoss.vscode-ansible
  - GrapeCity.gc-excelviewer
  - yzhang.markdown-all-in-one
  - DavidAnson.vscode-markdownlint
  - streetsidesoftware.code-spell-checker
  - eamodio.gitlens