---
# defaults file for ara
# If you would like to update the packages that this role installs, set `ara_packages_state` to `latest`, otherwise use `present`.
ara_package_state: present

# The ansible.cfg to modify.
ara_configuration_file: ./ansible.cfg

# Extra options can be set using this structure.
ara_configuration:
#   - option: port
#     value: 9191
#   - option: host
#     value: 0.0.0.0
#   - option: playbook_per_page
#     value: 10
#   - option: result_per_page
#     value: 25
    - option: database
      value: sqlite:////var/www/ara/.ara/ansible.sqlite
      